### ISSUE TITLE
Ajustar indice ES e resolver pesquisa

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_ssm#1]
@jamilatta com docker-compose (usando dev.yml) levanta a instância de ES, e consigo indexar os dados (manage.py rebuild_index, manage.py update_index) o problema é com a busca (/search/) que retorna sempre vazio :disappointed:

**Comment by jamilatta** [comment]
Problema resolvido no PR https://github.com/scieloorg/opac_ssm/pull/7
