### ISSUE TITLE
Adicionar a capacidade de desligar a indexação do conteúdo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_ssm#102]
No SSM temos um sginal que fica ligado, porém existe momentos que precisamos desligar para que possamos realizar um processamento mais rápido e depois indexarmos o conteúdo manualmente.

**Comment by jfunez** [comment]
acredito que seja uma boa oportunidade para deixar o signal desligado e implementar um scheduled job  para dispara periodicamente a execução de indexação
