### ISSUE TITLE
Recuperação de Assets via API GRPC.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_ssm#28]
Para recuperar os ativos, devemos considerar os seguintes pontos: 

* Recuperar pelos campos de metadados(JSON)
* Recuperar pela chave gerada no momento do cadastro do registro
* Garantir que cada "entrada" nos metadados sejam recuperáveis/pesquisáveis 
* Criar dois endpoints um retornando uma string de bytes do ativo e outro retornando a URL(Priorizar URL).

**IMPORTANTE**: Verificar como será indexado o JSON no ES.

**Comment by jamilatta** [comment]
Agora o PR #30 esta contemplando todos os itens.

**Comment by jfunez** [comment]
revisado e aprovado!
