### ISSUE TITLE
Forbidden (403) no momento de cadastrar de um usuário

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_ssm#33]
Suspeitamos que as configuração da aplicação para produção(docker-compose.yml) não esteja ajustada suficientemente para que o envio de e-mail funcione. 

<img width="1437" alt="screenshot 2017-01-12 11 24 54" src="https://cloud.githubusercontent.com/assets/373745/21891626/c006d0ec-d8ba-11e6-8275-9482ad41eb3a.png">

**Comment by jfunez** [comment]
Resposta e solução: https://github.com/scieloorg/opac_ssm/issues/69#issuecomment-279439887
