### ISSUE TITLE
Possibilidade de indicar um bucket (pelo nome) na hora de cadastrar um Asset

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_ssm#60]
Para agilizar o depósito de estáticos utilizando a interface gRPC, pensamos em realizar estes ajustes:

- adicionar uma função "get_or_create" para obter (ou criar se não existe) um bucket, identificando o bucket pelo nome.
- adicionar a possibilidade de indicar o bucket (pelo nome) na função add_asset via api gRPC.
- atualizar esta nova funcionalidade no projeto [SSM API](https://github.com/scieloorg/opac_ssm_api)

**Comment by jamilatta** [comment]
Importante para essa atividade: http://stackoverflow.com/questions/1941212/correct-way-to-use-get-or-create

**Comment by jfunez** [comment]
feito!
