### ISSUE TITLE
[BUG] erro no ES criando buckets (indice) ou assets

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_ssm#69]
Erro no sentry:
https://homolog.ssm.scielo.org/admin/assets_manager/assetbucket/add/

Passos para reproduzir o erro:
1. Acessar o Admin
2. Criar um novo bucket
3. Gera um erro Bad gateway (e registra erro: 👆 no sentry)

1. Acessar o Admin
2. Criar um novo Asset
3. Gera um erro Bad gateway (e registra erro: 👆 no sentry)

**Comment by jamilatta** [comment]
Pessoal, 

Esse erro foi resolvido. A forma que foi resolvido foi estranha, mas suponho que a combinação de fatos acabou por resolver....

Hipoteses: 

H0: Ao removermos as aspas da porta do elasticsearch 
H1: Ao Atualizarmos uma dependência do ES, PR: https://github.com/scieloorg/opac_ssm/pull/70
H2: A combinação de todas as anteriores

Para realizar essa tarefa concluir que não é possível utilizar a aplicação com os mesmos parâmetros da homologação. Homologação está configurada para funcionar com HTTPS e existe no arquivo de configuração "production.py", bastante parâmetros do Django considerando um serviço rodando em HTTPS.

Para resolver isso e rodarmos em máquina de desenvolvimento é preciso comentar as seguintes linhas: 

```python 
SECURE_HSTS_SECONDS = 60
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
   'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
SECURE_CONTENT_TYPE_NOSNIFF = env.bool(
   'DJANGO_SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'
```

Como a solução do problema foi corrigido por alguma das hipoteses, não existe PR.
